schema: "classroom50/repo-config/v1"
classroom: "comp-bio-skills-2026"
assignment: "lecture-1"
owner:
  username: "cbird808"
  id: 12803659
  accepted_at: "2026-09-04T14:49:32Z"
source:
  owner: "comp-bio-master"
  owner_id: 54107743
  repo: "lecture-1"
  branch: "main"
